/*
 * RemoteImage.java
 *
 * 
 */



import java.awt.*;
import javax.swing.*;
import java.io.*;
import java.awt.image.*;
import javax.imageio.*;
import java.util.*;
import java.text.*;

public class RemoteImage extends javax.swing.JFrame {
    
    /** Creates new form RemoteImage */
    public RemoteImage() {
            setTitle("Image Captured...");
            setBackground(Color.WHITE);
            getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER,0,0));
            initComponents();
            setSize(1000,800);
            setVisible(true);
            
    }
    
    public void updateScreen(ImageIcon ii)
    {try{
        jLabel1.setIcon(ii);
		Image img = ii.getImage();
		BufferedImage bi = new BufferedImage(img.getWidth(null),img.getHeight(null),BufferedImage.TYPE_INT_RGB);
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HHmmss");
Date date = new Date();
System.out.println(dateFormat.format(date));
Graphics2D g2 = bi.createGraphics();
g2.drawImage(img, 0, 0, null);
g2.dispose();
ImageIO.write(bi, "jpg", new File("img"+dateFormat.format(date)+".jpg"));
	
	}catch(Exception e){}
        repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
